title: "Cálculo Numérico"
description: "Notas de aula — Dr. José Walter Cárdenas Sotil"
theme: just-the-docs

url: "https://github.com/jowal60/calculo-numerico"

collections:
  01-aritmetica:
    output: true
    permalink: /aritmetica/:path/
  02-zeros:
    output: true
    permalink: /zeros/:path/
  03-sistemas-lineares:
    output: true
    permalink: /sistemas-lineares/:path/

just_the_docs:
  collections:
    01-aritmetica:
      name: "Aritmética"
    02-zeros:
      name: "Zeros de Funções"
    03-sistemas-lineares:
      name: "Sistemas Lineares"
